### ISSUE TITLE
Issue with commands documentation

### ISSUE THREAD

**Issue by ajitbohra** [wp-cli/handbook#202]
![commands_issue](https://user-images.githubusercontent.com/1039236/35765987-49614136-08f5-11e8-9805-9d8067ad60fd.jpg)

https://developer.wordpress.org/cli/commands/

**Comment by gitlost** [comment]
Thanks @ajitbohra .

**Comment by schlessera** [comment]
Currently working through the DevHub code to debug.

The issue of post duplication is due to the fact that CPT slugs share a namespace with other CPTs, and we hit this with commands like `embed`. The entire synchronization mechanism is built around the URL, and the `embed` command that has conflict with _some_ other post on the site is created under the slug `embed-2`. This causes every request to detect the entry as an existing parent to fail and parents are re-created all the time.

**Comment by schlessera** [comment]
Related: https://meta.trac.wordpress.org/ticket/3421

**Comment by ajitbohra** [comment]
Duplicate post issue is fixed. still, descriptions are empty & command content pages are blank.
![no_descriptions](https://user-images.githubusercontent.com/1039236/35852153-249ae66a-0b50-11e8-8ffb-694d66d73810.jpg)
![no_content](https://user-images.githubusercontent.com/1039236/35852164-2d657d3c-0b50-11e8-8e5e-88269908b26e.jpg)

**Comment by schlessera** [comment]
All commands should be available again.
